# Generated by Django 4.2.11 on 2024-06-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0135_hubhomepage_primary_colour_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericdata",
            name="areas",
            field=models.ManyToManyField(related_name="generic_data", to="hub.area"),
        ),
    ]