# Generated by Django 4.2.11 on 2024-06-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0136_genericdata_areas"),
    ]

    operations = [
        migrations.RenameField(
            model_name="externaldatasource",
            old_name="geography_column",
            new_name="point_field",
        ),
        migrations.RenameField(
            model_name="externaldatasource",
            old_name="geography_column_type",
            new_name="point_field_type",
        )
    ]
