# Generated by Django 4.2.11 on 2024-06-22 01:35

from django.db import migrations, models
import django_choices_field.fields
import hub.models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0137_add_more_geography_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaldatasource",
            name="polygon_field",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="externaldatasource",
            name="polygon_field_type",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("WARD", "Ward"),
                    ("ADMIN_DISTRICT", "Council"),
                    ("PARLIAMENTARY_CONSTITUENCY", "Constituency"),
                    ("PARLIAMENTARY_CONSTITUENCY_2025", "Constituency (2024)"),
                ],
                choices_enum=hub.models.ExternalDataSource.PolygonFieldTypes,
                default="PARLIAMENTARY_CONSTITUENCY_2025",
                max_length=31,
            ),
        ),
        migrations.AlterField(
            model_name="externaldatasource",
            name="point_field_type",
            field=django_choices_field.fields.TextChoicesField(
                choices=[("ADDRESS", "Address"), ("POSTCODE", "Postcode")],
                choices_enum=hub.models.ExternalDataSource.PointFieldTypes,
                default="POSTCODE",
                max_length=8,
            ),
        ),
    ]
