# Generated by Django 4.2.11 on 2024-06-22 01:35

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):
    dependencies = [
        ("hub", "0138_externaldatasource_polygon_field_and_more"),
    ]

    operations = [TrigramExtension()]