# Generated by Django 4.2.11 on 2024-06-22 02:27

from django.db import migrations
import django_choices_field.fields
import hub.models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0139_enable_trigrams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaldatasource",
            name="point_field_type",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[("ADDRESS", "Address"), ("POSTCODE", "Postcode")],
                choices_enum=hub.models.ExternalDataSource.PointFieldTypes,
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="externaldatasource",
            name="polygon_field_type",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("WARD", "Ward"),
                    ("ADMIN_DISTRICT", "Council"),
                    ("PARLIAMENTARY_CONSTITUENCY", "Constituency"),
                    ("PARLIAMENTARY_CONSTITUENCY_2025", "Constituency (2024)"),
                ],
                choices_enum=hub.models.ExternalDataSource.PolygonFieldTypes,
                max_length=31,
                null=True,
            ),
        ),
    ]
